#' Annotate cells based on marker enrichment
#'
#' Classifies individual cells into broad categories based on the co-expression of defined
#' marker genes. Unlike \code{\link{annotate_broad_clusters}}, this function operates on a
#' per-cell basis, ignoring existing cluster assignments.
#'
#' @details
#' \strong{Enrichment Logic:}
#' For each category in \code{broad_marker_list}, the function calculates a binary match vector:
#' \itemize{
#'   \item A cell is considered a "match" if it expresses at least \code{coexp_min} markers
#'   above the \code{expr_threshold}.
#' }
#'
#' \strong{Priority Resolution:}
#' If a cell matches multiple categories (e.g., matching both "T_cell" and "Immune"), the conflict
#' is resolved using the \code{priority} field in the configuration:
#' \itemize{
#'   \item The function iterates through categories from \strong{lowest priority} (highest number)
#'   to \strong{highest priority} (lowest number).
#'   \item Because assignments are overwritten sequentially, the category with the highest priority
#'   (lowest numeric rank) wins.
#' }
#'
#' \strong{Normalisation:}
#' If the Seurat object contains raw counts, this function attempts to run \code{Seurat::NormalizeData}
#' internally before checking expression thresholds.
#'
#' @param sObj A Seurat object.
#' @param broad_marker_list A valid configuration list generated by \code{\link{build_broad_marker_config}}.
#'   Must contain \code{markers}, \code{expr_threshold}, \code{coexp_min}, and \code{priority} for each category.
#' @param out_label_col Character. The name of the metadata column where the labels will be stored.
#' @param filter_features Character vector or NULL. If provided, subsets the Seurat object to these
#'   features before checking counts (optimization step).
#' @param unassigned_lab Character. The label assigned to cells that do not meet the co-expression
#'   criteria for any category. Default is "Other".
#'
#' @return A Seurat object with updated metadata in \code{out_label_col}.
#'
#' @export
annotate_broad_cells <- function(
    sObj,
    broad_marker_list,
    out_label_col,
    filter_features = NULL,
    unassigned_lab = "Other"
) {
  # Input checks ----

  if(missing(out_label_col)) cli::cli_abort("missing output column name for broad cell labels")

  .valid_sObj_input(sObj)

  sObj <- tryCatch({
    .is_norm_sObj(sObj)
    sObj

  }, error = function(e) {
    cli::cli_alert_info("Normalising count data ...")
    Seurat::NormalizeData(sObj, verbose = FALSE)
  })

  if (.valid_broad_marker_struct(broad_marker_list)) {
    all_broad_markers <- unlist(lapply(broad_marker_list, `[[`, "markers"), use.names = FALSE)
  } else{
    cli::cli_abort("Please use {.fn build_broad_marker_config} to generate a valid broad_marker_list.")
  }

  if(!is.null(filter_features)) sObj <- .filter_sObj_features(sObj, filter_features)

  .check_missing_feats(set1 = all_broad_markers, rownames(sObj))

  # Broad category marker counts ----
  cli::cli_progress_step("Assigning broad labels based on expression counts...", spinner = TRUE)

  expr_mat <- Seurat::GetAssayData(sObj, layer = "data")

  check_broad_category_counts <- function(broad_cat) {
    config <- broad_marker_list[[broad_cat]]
    counts <- Matrix::colSums(expr_mat[config$markers, , drop = FALSE] > config$expr_threshold)
    return(counts >= config$coexp_min)
  }

  matches <- vapply(
    X = names(broad_marker_list),
    FUN = check_broad_category_counts,
    FUN.VALUE = logical(ncol(expr_mat))
  )

  # Co-expression and broad category priority logic ----
  cli::cli_progress_step("Applying priority logic...", spinner = TRUE)

  get_priority <- function(config) {
    if (is.null(config$priority) || !is.numeric(config$priority)) {
      cli::cli_abort("Category config is missing a numeric 'priority' field.")
    }
    return(config$priority)
  }

  prio_vec <- vapply(broad_marker_list, get_priority, numeric(1))
  sorted_cats <- names(sort(prio_vec, decreasing = TRUE))

  assignment <- rep(unassigned_lab, ncol(expr_mat))

  for (cat_name in sorted_cats) {
    assignment[matches[, cat_name]] <- cat_name
  }

  sObj[[out_label_col]] <- assignment

  return(sObj)
}
