#' Generate subcluster labels within broad cell groups
#'
#' Runs \code{\link[scran]{quickSubCluster}} to subcluster cells within an
#' existing broad grouping, returning a single vector of subcluster labels.
#'
#' For each broad group in \code{group_col}, the function subsets the cells,
#' performs PCA on either:
#' \itemize{
#'   \item recomputed highly variable genes (\code{feature_mode = "hvg"}), or
#'   \item all genes present in the subset (\code{feature_mode = "all"})
#' }
#' and then builds an SNN graph followed by Leiden clustering.
#'
#' PCA dimensionality and graph-clustering parameters are estimated separately
#' for each subset using \code{\link{estimate_cluster_params}}, allowing the
#' workflow to adapt to the number of cells in each broad group.
#'
#' @param sce A \code{\link[SingleCellExperiment]{SingleCellExperiment}}
#'   containing a \code{logcounts} assay.
#' @param group_col Character scalar. Name of the column in
#'   \code{colData(sce)} containing the broad group labels to be subclustered.
#'   Defaults to \code{"broad_cluster"}.
#' @param feature_mode Character scalar specifying the feature space used for
#'   PCA within each broad subset. One of:
#'   \describe{
#'     \item{\code{"hvg"}}{Recompute gene variance within each subset using
#'       \code{\link[scran]{modelGeneVar}} and run PCA on the top highly
#'       variable genes defined by \code{hvg_prop}.}
#'     \item{\code{"all"}}{Run PCA on all genes present in the subset without
#'       recomputing highly variable genes.}
#'   }
#' @param out_col Character scalar or \code{NULL}. If \code{NULL} (default),
#'   the function returns only the subcluster label vector. If supplied, the
#'   labels are written to \code{colData(sce)[[out_col]]} as a factor and the
#'   modified \code{sce} is returned.
#' @param subcluster_col_fmt Character scalar. Format string passed to
#'   \code{\link[scran]{quickSubCluster}} via \code{format}. This controls how
#'   final subcluster labels are constructed. Defaults to \code{`\%s_sc\%s`}.
#' @param hvg_prop Numeric scalar in \code{(0, 1]}. When the \code{feature_mode = "hvg"},
#' this is the proportion of genes that are retained as highly variable within each broad subset.
#' For example, the default of \code{0.1} means that the top 10\% of genes
#' ranked by variance modelling will be used.
#
#' @param min_ncells Integer scalar. Minimum number of cells required for a
#'   broad group to be subclustered. Groups smaller than this threshold are not
#'   subclustered by \code{\link[scran]{quickSubCluster}}. Defaults to
#'   \code{50}. This value is passed directly to \code{min.ncells} in
#'    \code{\link[scran]{quickSubCluster}} and aligns with its default,
#'    which is based on empirical observations of when subclustering becomes unreliable.
#' @param seed Integer scalar. Random seed used before running subclustering.
#'   Defaults to \code{1234}.
#' @param BPPARAM A \code{\link[BiocParallel]{BiocParallelParam}} object used
#'   for parallelisation. Defaults to \code{\link[BiocParallel]{SerialParam}()}.
#'
#' @details
#' This function assumes that \code{sce} has already been normalised and
#' contains a \code{logcounts} assay. No additional normalisation is performed
#' inside \code{\link[scran]{quickSubCluster}}.
#'
#' Within each broad subset, PCA is performed using
#' \code{\link[scran]{fixedPCA}} and clustering is performed using
#' \code{\link[scran]{clusterCells}} with a
#' \code{\link[bluster]{SNNGraphParam}} configured for Leiden clustering.
#'
#' The PCA rank and clustering parameters are estimated independently for each
#' subset using \code{\link{estimate_cluster_params}}.
#'
#' The output is simplified, so only the final subcluster labels are returned,
#' as generated by \code{\link[scran]{quickSubCluster}} using the supplied
#' \code{subcluster_col_fmt}.
#'
#' @return
#' If \code{out_col = NULL}, returns a character vector of subcluster labels,
#' one per cell in \code{sce}, as returned by
#' \code{\link[scran]{quickSubCluster}} with \code{simplify = TRUE}.
#'
#' If \code{out_col} is supplied, returns the input
#' \code{\link[SingleCellExperiment]{SingleCellExperiment}} with the subcluster
#' labels added to \code{colData(sce)[[out_col]]} as a factor.
#'
#' @examples
#' \dontrun{
#' subclusters <- subcluster_labels(
#'   sce = sce,
#'   group_col = "broad_cluster",
#'   feature_mode = "hvg"
#' )
#'
#' sce <- subcluster_labels(
#'   sce = sce,
#'   group_col = "broad_cluster",
#'   feature_mode = "all",
#'   out_col = "broad_subcluster"
#' )
#' }
#'
#' @export
subcluster_labels <- function(sce,
                              group_col = "broad_cluster",
                              feature_mode = c("hvg", "all"),
                              out_col = NULL,
                              subcluster_col_fmt = "%s_sc%s",
                              hvg_prop = 0.1,
                              min_ncells = 50, # Aligns with the scran::quickSubCluster default
                              seed = 1234,
                              BPPARAM = BiocParallel::SerialParam()
) {

  if (!inherits(sce, "SingleCellExperiment")) cli::cli_abort("{.arg sce} must be a {.cls SingleCellExperiment}.")

  if (!group_col %in% colnames(SummarizedExperiment::colData(sce))) cli::cli_abort("Column {.val {group_col}} was not found in {.fn colData}.")

  if (!"logcounts" %in% SummarizedExperiment::assayNames(sce)) {
    cli::cli_abort(
      c(
        "Missing {.val logcounts} assay.",
        "i" = "Please run {.fn normalize_counts} before {.fn subcluster_labels}."
      )
    )
  }

  checkmate::assert_number(hvg_prop, lower = 0, upper = 1)
  checkmate::assert_count(min_ncells, positive = TRUE)

  if (!is.null(out_col)) checkmate::assert_string(out_col, min.chars = 1)

  feature_mode <- match.arg(feature_mode, several.ok = FALSE, choices = c("hvg", "all"))

  # Identify which broad groups will be skipped for subclustering due to low cell counts
  group_vec <- as.character(SummarizedExperiment::colData(sce)[[group_col]])
  group_counts <- table(group_vec)

  skipped_groups <- names(group_counts)[group_counts < min_ncells]

  if (length(skipped_groups) > 0) {

    cli::cli_alert_info(
      "{cli::qty(length(skipped_groups))}The following broad categor{?y/ies} {?has/have} < {min_ncells} cells and will be skipped: {.val {skipped_groups}}"
    )
  }

  set.seed(seed)

  subcluster_out <- scran::quickSubCluster(
    x = sce,
    groups = as.character(SummarizedExperiment::colData(sce)[[group_col]]),
    normalize = FALSE,
    assay.type = "logcounts",
    min.ncells = min_ncells,
    format = subcluster_col_fmt,
    simplify = TRUE,

    prepFUN = function(x) {

      subset_row <- NULL

      if (feature_mode == "hvg") {
        dec <- scran::modelGeneVar(x)
        hvgs <- scran::getTopHVGs(dec, prop = hvg_prop)
        subset_row <- hvgs
      }

      n_features <- if(is.null(subset_row)) nrow(x) else length(subset_row)

      est_params <- suppressMessages({estimate_cluster_params(n_cells = ncol(x))})

      max_rank <- min(est_params$n_pcs, n_features - 1L, ncol(x) - 1L)

      # Silent fall-back : If PCA is impossible, return the object without PCA.
      if (max_rank < 1L) return(x)

      cluster_input <- scran::fixedPCA(
        x = x,
        subset.row = subset_row,
        name = "sub_PCA",
        rank = max_rank,
        BPPARAM = BPPARAM
      )

      return(cluster_input)
    },

    clusterFUN = function(x) {

      # If PCA was skipped in prepFUN, return a single cluster label (1)

      if (!"sub_PCA" %in% SingleCellExperiment::reducedDimNames(x)) return(rep(1L, ncol(x)))

      est_params <- suppressMessages({estimate_cluster_params(n_cells = ncol(x))})

      k_eff <- min(est_params$k, ncol(x) - 1L)

      if (k_eff < 1L) return(rep(1L, ncol(x)))

      g <- scran::clusterCells(
        x = x,
        use.dimred = "sub_PCA",
        BLUSPARAM = bluster::SNNGraphParam(
          k = k_eff,
          cluster.fun = "leiden",
          cluster.args = list(
            resolution_parameter = est_params$resolution,
            objective_function = "modularity"
          )
        )
      )

      return(g)
    }
  )

  if (is.null(out_col)) return(subcluster_out)

  sce[[out_col]] <- factor(subcluster_out)

  return(sce)

}


#' Extract top marker genes from ranked marker tables
#'
#' Generates a list of marker genes per cluster using ranked marker tables
#' produced by \code{\link{rank_cluster_markers}}.
#'
#' Ranked marker tables may be supplied either:
#' \itemize{
#'   \item directly via the \code{ranked_markers} argument, or
#'   \item indirectly via \code{metadata(sce)[[ranked_markers_key]]}.
#' }
#'
#' If \code{ranked_markers} is supplied, it takes precedence and \code{sce} is
#' only used for class consistency. In that case, \code{ranked_markers_key} is
#' ignored.
#'
#' Genes are first ordered by:
#' \enumerate{
#'   \item ascending \code{FDR}, and
#'   \item descending effect size (AUC for Wilcoxon, logFC for t-tests).
#' }
#'
#' Marker genes passing:
#' \itemize{
#'   \item \code{FDR <= fdr_threshold}, and
#'   \item \code{effect size >= effect_threshold}
#' }
#' are prioritised. The final output for each cluster consists of exactly
#' \code{target_n} genes: passing genes are included first, then remaining
#' slots are filled with top-ranked genes that did not pass thresholds.
#'
#' This ensures a consistent gene set size across clusters while prioritising
#' high-confidence markers for downstream enrichment analysis.
#'
#' @param sce A \code{\link[SingleCellExperiment]{SingleCellExperiment}}.
#'   Required only when \code{ranked_markers} is not supplied.
#' @param ranked_markers_key Character scalar. Metadata entry containing ranked
#'   marker tables. Defaults to \code{"broad_cluster_markers"}.
#' @param ranked_markers List or \code{NULL}. Ranked marker result returned by
#'   \code{\link{rank_cluster_markers}(return_list = TRUE)}. If supplied, this
#'   takes precedence over \code{sce} and \code{ranked_markers_key}.
#' @param fdr_threshold Numeric scalar. Maximum FDR threshold. Defaults to
#'   \code{0.05}.
#' @param effect_threshold Numeric scalar. Minimum effect size threshold.
#'   Defaults to \code{0.6}.
#' @param target_n Integer scalar. Number of genes to return per cluster.
#'   Defaults to \code{100L}.
#'
#' @return A named list with one entry per cluster, each containing:
#'   \describe{
#'     \item{\code{top_n}}{Character vector of up to \code{target_n} genes,
#'       passing genes first, then supplemented backfill.}
#'     \item{\code{supplemented}}{Character vector of backfill genes that did
#'       not meet the FDR/effect thresholds. Empty character vector if all
#'       \code{target_n} slots were filled by passing genes.}
#'   }
#'
#' @export
extract_top_markers <- function(sce = NULL,
                                ranked_markers_key = "broad_cluster_markers",
                                ranked_markers = NULL,
                                fdr_threshold = 0.05,
                                effect_threshold = 0.6,
                                target_n = 100L
                                ) {

  checkmate::assert_number(fdr_threshold,   lower = 0, upper = 1)
  checkmate::assert_number(effect_threshold, lower = 0)
  checkmate::assert_count(target_n, positive = TRUE)

  if (!is.null(ranked_markers_key)) checkmate::assert_string(ranked_markers_key, min.chars = 1)

  rank_res <- .resolve_ranked_markers(sce, ranked_markers, ranked_markers_key)

  if (!is.list(rank_res) || !all(c("marker_tables", "params") %in% names(rank_res))) {
    cli::cli_abort("Ranked marker input must be a list with {.val marker_tables} and {.val params} entries.")
  }

  marker_tables <- rank_res$marker_tables
  test_type     <- rank_res$params$test_type

  if (length(marker_tables) == 0L) cli::cli_abort("No marker tables found in ranked marker input.")

  eff_col <- switch(test_type, wilcox = "summary.AUC", "summary.logFC")

  if (!eff_col %in% colnames(marker_tables[[1L]])) {
    cli::cli_abort("Expected effect-size column {.val {eff_col}} not found in marker tables.")
  }

  top_markers <- lapply(names(marker_tables), function(cluster_id) {
    .extract_cluster_top_markers(
      tab              = as.data.frame(marker_tables[[cluster_id]]),
      eff_col          = eff_col,
      fdr_threshold    = fdr_threshold,
      effect_threshold = effect_threshold,
      target_n         = target_n
    )
  })
  names(top_markers) <- names(marker_tables)

  needs_backfill <- names(Filter(function(x) length(x$supplemented) > 0L, top_markers))
  print_alert("Supplemented cluster{?s}: {.val {needs_backfill}}", type = "i")

  return(top_markers)
}

#' Resolve ranked marker source
#'
#' Returns the ranked marker list, either from the argument directly or from
#' SCE metadata. Centralises the resolution logic so the main function stays
#' readable.
#'
#' @noRd
#' @keywords internal
.resolve_ranked_markers <- function(sce, ranked_markers, ranked_markers_key) {

  if (!is.null(ranked_markers)) return(ranked_markers)

  if (is.null(sce)) cli::cli_abort("Provide either {.arg ranked_markers} directly or {.arg sce} with a valid {.arg ranked_markers_key}.")

  if (!inherits(sce, "SingleCellExperiment")) cli::cli_abort("{.arg sce} must be a {.cls SingleCellExperiment}.")

  meta_names <- names(S4Vectors::metadata(sce))

  if (!ranked_markers_key %in% meta_names) {
    cli::cli_abort(
      "Metadata key {.val {ranked_markers_key}} not found in {.arg sce}. \\
       Available keys: {.val {meta_names}}."
    )
  }

  return(S4Vectors::metadata(sce)[[ranked_markers_key]])
}


#' Extract top N markers for a single cluster
#'
#' Sorts the marker table, identifies passing genes, fills to \code{target_n}
#' with backfill genes if needed, and returns the two-slot result list.
#'
#' @noRd
#' @keywords internal
.extract_cluster_top_markers <- function(tab,
                                         eff_col,
                                         fdr_threshold,
                                         effect_threshold,
                                         target_n) {

  tab <- tab[order(tab$FDR, -tab[[eff_col]]), , drop = FALSE]

  all_genes         <- rownames(tab)
  passes_thresholds <- tab$FDR <= fdr_threshold & tab[[eff_col]] >= effect_threshold

  passing_genes    <- all_genes[passes_thresholds]
  non_passing_genes <- all_genes[!passes_thresholds]

  n_supplemented_needed <- max(0L, target_n - length(passing_genes))
  supplemented_genes    <- S4Vectors::head(non_passing_genes, n_supplemented_needed)

  top_n <- c(passing_genes, supplemented_genes)

  if (length(top_n) > target_n) {
    top_n <- top_n[seq_len(target_n)]
    supplemented_genes <- character(0)
  }

  return(
    list(top_n = top_n, supplemented = supplemented_genes)
  )
}



#' Score cluster marker genes against fine cell type marker panels
#'
#' For each cluster, identifies the relevant subset of the fine cell type
#' marker panel based on the broad label encoded in the cluster name, then
#' scores overlap using Fisher's exact test and overlap similarity.
#'
#' Cluster names are expected to follow the convention \code{"<broad>_sc<N>"},
#' e.g. \code{"immune_sc1"}, \code{"vasculature_sc2"}. The broad prefix is
#' matched against the top-level names of \code{marker_panel}.
#'
#' \strong{Edge case — collapsed broad labels:} When all clusters share the
#' same broad label (e.g. all assigned \code{"other"}), downstream
#' subclustering produces names like \code{"1_sc1"}, \code{"2_sc2"} whose
#' prefix is numeric and does not resolve to a panel entry. In this situation
#' the function tests against \emph{all} marker sets in the panel.
#'
#' @param top_markers Named list. Output of \code{\link{extract_top_markers}};
#'   each element must contain a \code{top_n} character vector.
#' @param marker_panel Named list of named lists. Top-level names are broad
#'   cell-type categories (e.g. \code{"immune"}, \code{"vasculature"},
#'   \code{"other"}); inner names are fine cell types; values are character
#'   vectors of marker genes.
#' @param background_genes Character vector. Full set of genes in the dataset,
#'   used as the background population for Fisher's exact test.
#'
#' @return A \code{data.frame} with columns:
#'   \describe{
#'     \item{\code{cluster_name}}{Cluster identifier from \code{top_markers}.}
#'     \item{\code{marker_set_name}}{Fine cell type name from the panel.}
#'     \item{\code{fisher_p}}{P-value from Fisher's exact test.}
#'     \item{\code{similarity}}{Overlap similarity score.}
#'   }
#'   Rows are ordered by \code{cluster_name} then ascending \code{fisher_p}.
#'
#' @export
score_markers_against_panel <- function(top_markers, marker_panel, background_genes) {

  checkmate::assert_list(top_markers, names = "named", min.len = 1L)
  checkmate::assert_list(marker_panel, names = "named", min.len = 1L)
  checkmate::assert_character(background_genes, min.len = 1L, any.missing = FALSE)

  bad_slots <- !vapply(
    X         = top_markers,
    FUN       = function(x) is.list(x) && "top_n" %in% names(x) && is.character(x$top_n),
    FUN.VALUE = logical(1L)
  )

  if (any(bad_slots)) {
    cli::cli_abort(
      "The following {.arg top_markers} entries are missing a character {.val top_n} slot: \\
       {.val {names(top_markers)[bad_slots]}}."
    )
  }

  broad_categories  <- names(marker_panel)
  cluster_names     <- names(top_markers)

  broad_labels <- vapply(cluster_names, .parse_broad_label, character(1L))
  all_numeric  <- all(is.na(broad_labels))
  unrecognised <- !is.na(broad_labels) & !broad_labels %in% broad_categories

  if (all_numeric) {
    n_sets <- length(unlist(marker_panel, recursive = FALSE))

    print_alert(
      c("All cluster names have numeric prefixes.",
       "\n  - likely due to collapsed broad label (e.g. all clusters assigned 'other').",
       "\n  - Testing all clusters against all {n_sets} marker sets."),
      type = "i"
    )

  } else if (any(unrecognised)) {

    print_alert(
      c("Some cluster names have unrecognised broad labels:",
       "\n  - {.val {unique(broad_labels[unrecognised])}}",
       "\n  - Testing affected clusters against the full panel."),
      type = "w"
    )
  }

  results <- lapply(cluster_names, function(cluster_id) {

    query_genes   <- top_markers[[cluster_id]]$top_n
    broad_label   <- .parse_broad_label(cluster_id)
    active_panel <- .resolve_panel_subset(broad_label, marker_panel, broad_categories)

    cluster_scores <- lapply(names(active_panel), function(marker_set_name) {

      reference_genes <- active_panel[[marker_set_name]]

      fisher_p  <- fisher_score(
        set1 = query_genes,
        set2 = reference_genes,
        background = background_genes,
        return_pval = TRUE
        )

      similarity <- calculate_similarity(
        cluster_genes = query_genes,
        ref_genes = reference_genes
        )

      score_df <- data.frame(cluster_name     =   cluster_id,
                             marker_set_name  =   marker_set_name,
                             fisher_p         =   fisher_p,
                             similarity       =   similarity,
                             stringsAsFactors =   FALSE
                             )
      return(score_df)

    })

    return(dplyr::bind_rows(cluster_scores))

  })

  out <- dplyr::bind_rows(results)

  # cluster order preserved > best Fisher p first within each cluster
  out <- out[order(match(out$cluster_name, cluster_names), out$fisher_p), ]

  return(out)
}


#' Parse the broad label prefix from a cluster name
#'
#' Extracts everything before the last \code{_sc<digits>} suffix.
#' Returns \code{NA_character_} if the prefix is purely numeric (edge case).
#'
#' @examples
#' \dontrun{
#' .parse_broad_label("immune_sc1")       # "immune"
#' .parse_broad_label("other_sc3")        # "other"
#' .parse_broad_label("my_broad_sc2")     # "my_broad"  (multi-part prefix)
#' .parse_broad_label("1_sc1")            # NA  → edge case
#'}
#'
#' @noRd
#' @keywords internal
.parse_broad_label <- function(cluster_name) {

  prefix <- sub("_sc\\d+$", "", cluster_name)

  if (identical(prefix, cluster_name) || grepl("^\\d+$", prefix)) return(NA_character_)

  return(prefix)
}


#' Resolve which panel subset to test a cluster against
#'
#' Returns the flat named list of fine marker sets relevant to this cluster.
#' If \code{broad_label} is \code{NA} or not found in the panel, all marker
#' sets across the entire panel are returned (edge case behaviour).
#'
#' @noRd
#' @keywords internal
.resolve_panel_subset <- function(broad_label, marker_panel, broad_categories) {

  use_full_panel <- is.na(broad_label) || !broad_label %in% broad_categories

  if (use_full_panel){

    out_panel <- unlist(marker_panel, recursive = FALSE)

    } else out_panel <- marker_panel[[broad_label]]

  out_panel <- stats::setNames(out_panel, sub("^[^.]+\\.", "", names(out_panel)))

  return(out_panel)

}


#' Calculate Fisher's Exact Test for gene set enrichment
#'
#' Performs a one-tailed Fisher's Exact Test to determine if the overlap between
#' a query set (e.g., cluster markers) and a reference set (e.g., cell type markers)
#' is statistically significant given a background universe of genes.
#'
#' @details
#' The function constructs a contingency table:
#' \tabular{cc}{
#'   In Both Sets (a) \tab In Set 1 Only (b) \cr
#'   In Set 2 Only (c) \tab In Neither (d)
#' }
#' It tests the alternative hypothesis that the true odds ratio is greater than 1
#' (enrichment). If \code{length(set1)} is greater than or equal to the background,
#' it assumes \code{set1} represents the entire universe and returns p = 1 (or NA).
#'
#' @param set1 Character vector. Query genes (e.g., DE markers from a cluster).
#' @param set2 Character vector. Reference genes (e.g., known markers for a cell type).
#' @param background Character vector. The "universe" of all detected genes in the experiment.
#' @param return_pval Logical. If \code{TRUE}, returns only the p-value. If \code{FALSE},
#'   returns the full \code{htest} object. Default is \code{TRUE}.
#'
#' @return A numeric p-value or a \code{htest} object.
#' @importFrom stats fisher.test
#'
#' @noRd
#' @keywords internal
fisher_score <- function(set1, set2, background, return_pval = TRUE) {

  if(!is.character(set1)) cli::cli_abort("set1 must be a character vector of gene names.")
  if(!is.character(set2)) cli::cli_abort("set2 must be a character vector of gene names.")
  if(!is.character(background)) cli::cli_abort("background must be a character vector of gene names.")

  # case when cluster and background are the same
  if (length(set1) >= length(background)) {
    return(ifelse(return_pval, 1, NA))
  }

  a <- length(intersect(set1, set2)) # overlap
  b <- length(set1) - a # in set1 only
  c <- length(set2) - a # in set2 only
  d <- length(background) - (a+b+c) # neither
  mat <- matrix(c(a, b, c, d), nrow = 2)
  out <- fisher.test(mat, alternative = "greater")

  if(return_pval) return(out$p.value) else return(out)
}



#' Compute the overlap coefficient between two gene sets
#'
#' @details
#' The overlap coefficient is defined as:
#' \deqn{O(A,B) = \frac{|A \cap B|}{\min(|A|, |B|)}}
#' Representing the intersection relative to the smaller set. This is
#' particularly useful when comparing a small reference marker panel against
#' a larger query gene set, as it is insensitive to differences in set size.
#' Returns \code{0} if either set is empty.
#'
#' @param cluster_genes Character vector. Genes in the cluster/query set.
#' @param ref_genes Character vector. Genes in the reference marker set.
#'
#' @return Numeric scalar in \code{[0, 1]}.
#'
#' @noRd
#' @keywords internal
calculate_similarity <- function(cluster_genes, ref_genes) {

  checkmate::assert_character(cluster_genes)
  checkmate::assert_character(ref_genes)

  cluster_genes <- unique(cluster_genes)
  ref_genes     <- unique(ref_genes)

  intersection <- length(intersect(cluster_genes, ref_genes))
  min_size     <- min(length(cluster_genes), length(ref_genes))

  if (min_size == 0L) return(0) else return(intersection / min_size)
}


#' Assign fine cell type labels from enrichment scores
#'
#' Selects the best-matching fine cell type label for each cluster based on
#' minimum Fisher p-value, with ties broken by descending overlap similarity.
#'
#' @param cluster_col Factor or character vector. Cluster identifiers per cell,
#'   typically a \code{colData} column from a
#'   \code{\link[SingleCellExperiment]{SingleCellExperiment}}. Values must
#'   match \code{cluster_name} entries in \code{scores}.
#' @param scores A \code{data.frame} as returned by
#'   \code{\link{score_markers_against_panel}}, with columns
#'   \code{cluster_name}, \code{marker_set_name}, \code{fisher_p}, and
#'   \code{similarity}.
#'
#' @return A named list containing:
#'   \describe{
#'     \item{\code{labels}}{Factor of fine cell type labels, one per cell,
#'       in the same order as \code{cluster_col}.}
#'     \item{\code{scores}}{A \code{data.frame} of the best label per cluster
#'       with columns \code{cluster_name}, \code{marker_set_name},
#'       \code{fisher_p}, and \code{similarity}.}
#'   }
#'
#' @export
assign_fine_labels <- function(cluster_col, scores) {

  checkmate::assert(
    checkmate::check_factor(cluster_col),
    checkmate::check_character(cluster_col)
  )

  checkmate::assert_data_frame(scores, min.rows = 1L)

  checkmate::assert_names(
    names(scores),
    must.include = c("cluster_name", "marker_set_name", "fisher_p", "similarity")
  )

  best_labels <- lapply(split(scores, scores$cluster_name),
                        function(cluster_scores) {

      cluster_scores <- cluster_scores[
        order(cluster_scores$fisher_p, -cluster_scores$similarity),
      ]

      out <- cluster_scores[1L, c("cluster_name",
                                  "marker_set_name",
                                  "fisher_p",
                                  "similarity")]
      return(out)
    })

  best_labels <- dplyr::bind_rows(best_labels)

  cell_clusters <- as.character(cluster_col)
  label_map     <- stats::setNames(best_labels$marker_set_name, best_labels$cluster_name)

  unmapped <- setdiff(unique(cell_clusters), names(label_map))

  if (length(unmapped) > 0L) {

    print_alert(
      c("Some clusters have no corresponding score entry:",
       "\n  - {.val {unmapped}}",
       "\n  - These will be labelled {.val NA}."),
      type = "w"
    )

  }

  cell_labels <- factor(unname(label_map[cell_clusters]))

  return(list(labels = cell_labels, scores = best_labels))

}
