#' Determine the best cluster labels from scores
#'
#' Identifies the top-ranking reference label for each cluster based on the
#' statistical scores generated by \code{\link{score_subclusters}}.
#'
#' @details
#' \strong{Ranking Logic:}
#' For each cluster, candidate labels are sorted using the following hierarchy:
#' \enumerate{
#'   \item \strong{p-value (Ascending):} The most statistically significant enrichment is preferred.
#'   \item \strong{Average Module Score (Descending):} Used as a tie-breaker if p-values are identical.
#'   \item \strong{Overlap Coefficient (Descending):} Used as a secondary tie-breaker.
#' }
#' The top result (slice 1) is selected as the "best" label.
#'
#' @param sub_score_df A data frame containing scoring results (output of \code{\link{score_subclusters}}).
#'   Must contain columns: \code{cluster}, \code{cell_label}, \code{pval}, \code{avg_module_score}, and \code{overlap_coef}.
#'
#' @return A named character vector.
#' \itemize{
#'   \item \strong{Names:} The new biological labels (e.g., "CD8+ T cells").
#'   \item \strong{Values:} The original cluster IDs (e.g., "0", "1").
#' }
#' This format is directly compatible with \code{forcats::fct_recode} (via the \code{!!!} splice operator).
#' @importFrom dplyr .data
#' @export
get_best_label <- function(sub_score_df){

  label_map <- sub_score_df %>%
    dplyr::group_by(.data$cluster) %>%
    # Order: lowest pval -> highest module score -> highest overlap
    dplyr::arrange(
      .data$pval,
      dplyr::desc(.data$avg_module_score),
      dplyr::desc(.data$overlap_coef)
    ) %>%
    dplyr::slice(1) %>%
    dplyr::ungroup() %>%
    dplyr::select(.data$cluster, best_label = .data$cell_label)

  label_map <- setNames(
    object = as.character(label_map$cluster),
    nm = as.character(label_map$best_label)
  )

  return(label_map)

}





#' Assign new biological labels to cells
#'
#' Updates the Seurat object metadata with new cell type labels based on the mapping
#' created by \code{\link{get_best_label}}.
#'
#' @details
#' This function handles two scenarios:
#' \itemize{
#'   \item \strong{Single Cluster:} Directly assigns the single label to the new column.
#'   \item \strong{Multiple Clusters:} Uses \code{forcats::fct_recode} to map old cluster IDs
#'   to new text labels.
#' }
#'
#' @param sub_sObj A Seurat object containing the sub-clustered cells.
#' @param sub_best_label_map A named character vector where names are the new labels
#'   and values are the old cluster IDs (output of \code{get_best_label}).
#' @param sub_sObj_col Character. The metadata column containing the current cluster IDs (must be a factor).
#' @param sub_sObj_new_col Character. The name of the new metadata column to create.
#'
#' @return A Seurat object with the new annotation column added.
#' @export
assign_labels <- function(
    sub_sObj,
    sub_best_label_map,
    sub_sObj_col,
    sub_sObj_new_col
){

  if(length(names(sub_best_label_map)) != length(sub_best_label_map)) {
    cli::cli_abort("The {.arg sub_best_label_map} must be a named vecotor with new labels as names")
  }

  missing_map_vals <- which(!sub_best_label_map %in% unique(sub_sObj@meta.data[[sub_sObj_col]]))

  if(length(missing_map_vals) > 0) {
    cli::cli_abort(c(
      "x" = "The following vals in {.arg sub_best_label_map} are not found in {.val {sub_sObj_col}}:",
      "i" = "{.val {sub_best_label_map[missing_map_vals]}}"
    ))

  }

  single_subcluster <- length(unique(sub_sObj@meta.data[[sub_sObj_col]])) == 1

  if(single_subcluster){

    sub_sObj@meta.data[[sub_sObj_new_col]] <- (names(sub_best_label_map))

  }else{

    if(!is.factor(sub_sObj@meta.data[[sub_sObj_col]])) {
      cli::cli_abort("The specified {.arg sub_sObj_col} ({.val {sub_sObj_col}}) must be a factor.")
    }

    sub_sObj@meta.data[[sub_sObj_new_col]] <- forcats::fct_recode(
      sub_sObj@meta.data[[sub_sObj_col]], !!!sub_best_label_map
    )

  }

  cli::cli_alert_success("Successfully assigned labels to column: {.val {sub_sObj_new_col}}")

  return(sub_sObj)
}
